"""
These functions are used to load data from a custom ScanImage data format
used in our experiments. The data are generated and saved by MATLAB scripts
that are not included in this repository.

ScanImage's DataRecorder should be used to record:
    - FrameOnset
    - StimTTL

Please also see:
BaselLaserMouse/ScanImageTools - Rob Campbell, Sumiya Kuroda
https://github.com/BaselLaserMouse/ScanImageTools/tree/2p-313
"""

from pathlib import Path

import h5py
import numpy as np
import pandas as pd


def read_h5_array(h5_path: Path, dataset_path: str) -> np.ndarray:
    """
    Read a dataset from an HDF5 file and return it as a NumPy array.

    Parameters
    ----------
    h5_path : str
        Path to the .h5 / .hdf5 file
    dataset_path : str
        Path inside the HDF5 file (e.g. 'SyncTTL' or '/group/dataset')

    Returns
    -------
    np.ndarray
        Dataset as a NumPy array
    """
    with h5py.File(h5_path, "r") as f:
        data = f[dataset_path][:]
    return data


def digitize_ai_signal(ai_signal, digitizeThr=4):
    ai_signal_digitized = np.array(ai_signal).copy()

    ai_signal_digitized[ai_signal < digitizeThr] = 0.0
    ai_signal_digitized[ai_signal >= digitizeThr] = 1.0

    return ai_signal_digitized


def find_edges(signal: np.ndarray, return_edges: str = "both"):
    signal = np.asarray(signal).astype(bool)

    diff = np.diff(signal.astype(np.int8))

    rising = np.where(diff == 1)[0] + 1
    falling = np.where(diff == -1)[0] + 1

    # If signal starts HIGH, first rising edge is at index 0
    if signal[0]:
        rising = np.insert(rising, 0, 0)

    # If signal ends HIGH, final falling edge is at last index
    if signal[-1]:
        falling = np.append(falling, len(signal) - 1)

    if return_edges == "rising":
        return rising
    elif return_edges == "falling":
        return falling
    elif return_edges == "both":
        return rising, falling


def get_artefact_dfs(
    path_to_h5: Path,
    channel_name_framettl: str,
    channel_name_stimttl: str,
    digitize_threshold: float = 4,
) -> tuple:
    """Read the HDF5 file generated by ScanImage's Data Recorder

    Parameters
    ----------
    path_to_h5 : Path
        Path to the HDF5 file.
    channel_name_framettl : str
        Name of the channel for frame clock.
    channel_name_stimttl : str
        Name of the channel for photostim TTL.
    digitize_threshold: float
        Threshold used to digitize analog signals

    Returns
    -------
    tuple
        tuple of pd.DataFrame
    """

    framettl = read_h5_array(path_to_h5, channel_name_framettl)
    stimttl = read_h5_array(path_to_h5, channel_name_stimttl)

    framettl_d = digitize_ai_signal(framettl, digitizeThr=digitize_threshold)
    stimttl_d = digitize_ai_signal(stimttl, digitizeThr=digitize_threshold)

    framettl_rising, framettl_falling = find_edges(framettl_d)
    stimttl_rising, stimttl_falling = find_edges(stimttl_d)

    df_frames = pd.DataFrame(
        {
            "start": framettl_rising,
            "stop": framettl_falling,
        }
    )

    df_stims = pd.DataFrame(
        {
            "start": stimttl_rising,
            "stop": stimttl_falling,
        }
    )

    return df_frames, df_stims
